name: CI to Github Pages

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-events-json:
    environment: perl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache ~/perl5
        uses: actions/cache@v2
        with:
          key: perl-locallib
          path: ~/perl5
      - name: Cache timezones
        uses: actions/cache@v2
        with:
          key: perl-timezone-cache
          path: ${{ github.workspace }}/cache
      - name: Install cpanm
        run: |
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
      - name: Install local::lib
        run: |
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - name: Install dependencies
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm --notest --installdeps .
      - name: Run the parser
        env:
          GEO_CACHE_DIR: ${{ github.workspace }}/cache
          GEO_USERNAME: ${{ secrets.GEO_USERNAME }}
        run: |
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          perl bin/parse.pl
      - name: Upload JSON
        uses: actions/upload-artifact@v2
        with:
          name: events
          path: ./events.json
  build-and-deploy-angular:
    needs: create-events-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Download events
        uses: actions/download-artifact@v2
        with:
          name: events
          path: .
      - name: Build Angular App
        run: npm run-script deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages 
          folder: gh-pages
         